spring:
  application:
    name: Personal-Expense-Tracker
  datasource:
    url: jdbc:mysql://localhost:3306/expense_tracker?useSSL=false
    username: root
    password: Amma@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 5008